### ISSUE TITLE
Four diagonal directions to aggregate information

### ISSUE THREAD

**Issue by Assioncreed** [gndlwch2w/msvm-unet#2]
Hi, I would like to know where exactly is the code that implements the aggregation of information from the four diagonal directions proposed in the paper?

**Comment by gndlwch2w** [comment]
Thank you for your attention to our work. In the paper, we mention the introduction of convolution operations in the feed-forward network to aggregate information from four diagonal directions. Specifically, for any feature point on the feature map, the convolution operation is able to aggregate features from all directions around it (including the diagonal directions). Through multiple stacked layers, the receptive field can be expanded, enabling the aggregation of diagonal features across the entire feature map. Moreover, to handle organs of various sizes and shapes, we employ multi-scale parallel convolutions on top of this. For specific code implementation, please refer to: [https://github.com/gndlwch2w/msvm-unet/blob/abb1a8ed5cf6f211a9c7b375feb7a40db0775960/model/decoder.py#L13](https://github.com/gndlwch2w/msvm-unet/blob/abb1a8ed5cf6f211a9c7b375feb7a40db0775960/model/decoder.py#L13)

**Comment by Assioncreed** [comment]
Thank you very much. I understand.
