### ISSUE TITLE
selective_scan_cuda_oflex

### ISSUE THREAD

**Issue by xiaogege1210** [gndlwch2w/msvm-unet#3]
I'd like to ask why I am encountering an error when running train_acdc: 

NameError: name 'selective_scan_cuda_oflex' is not defined.

**Comment by xiaogege1210** [comment]
I apologize for disturbing you again. I followed your instructions and tried to install using kernels/selective_scan, but I encountered an error during the installation. It said that my CUDA version (11.8) does not match the required CUDA version (12.1). I would like to ask what the situation is.

**Comment by gndlwch2w** [comment]
Please make sure your pytorch version (at least >= 2.0.0) matches your cuda version. I recommend using the version I provide. For details, please refer to: [https://pytorch.org/get-started/previous-versions/](https://pytorch.org/get-started/previous-versions/).

**Comment by xiaogege1210** [comment]
My email address is 1223056011@njupt.edu.cn

**Comment by gndlwch2w** [comment]
We submitted the code for related test visualization, please refer to: [https://github.com/gndlwch2w/msvm-unet/commit/be7dbe419fd5bdf0185700136f94fb7427b455f0.](https://github.com/gndlwch2w/msvm-unet/commit/be7dbe419fd5bdf0185700136f94fb7427b455f0.)
